package com.bjb.cultural.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.bjb.cultural.dao.BoxSubMenu;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BOX_SUB_MENU.
*/
public class BOX_SUB_MENU extends AbstractDao<BoxSubMenu, Void> {

    public static final String TABLENAME = "BOX_SUB_MENU";

    /**
     * Properties of entity BoxSubMenu.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property SUB_MENU_ID = new Property(0, String.class, "SUB_MENU_ID", false, "SUB_MENU_ID");
        public final static Property MAIN_MENU_ID = new Property(1, String.class, "MAIN_MENU_ID", false, "MAIN_MENU_ID");
        public final static Property SUB_MENU_NAME = new Property(2, String.class, "SUB_MENU_NAME", false, "SUB_MENU_NAME");
        public final static Property SHOW_SORT = new Property(3, Integer.class, "SHOW_SORT", false, "SHOW_SORT");
    };


    public BOX_SUB_MENU(DaoConfig config) {
        super(config);
    }
    
    public BOX_SUB_MENU(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BOX_SUB_MENU' (" + //
                "'SUB_MENU_ID' TEXT," + // 0: SUB_MENU_ID
                "'MAIN_MENU_ID' TEXT," + // 1: MAIN_MENU_ID
                "'SUB_MENU_NAME' TEXT," + // 2: SUB_MENU_NAME
                "'SHOW_SORT' INTEGER);"); // 3: SHOW_SORT
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BOX_SUB_MENU'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BoxSubMenu entity) {
        stmt.clearBindings();
 
        String SUB_MENU_ID = entity.getSUB_MENU_ID();
        if (SUB_MENU_ID != null) {
            stmt.bindString(1, SUB_MENU_ID);
        }
 
        String MAIN_MENU_ID = entity.getMAIN_MENU_ID();
        if (MAIN_MENU_ID != null) {
            stmt.bindString(2, MAIN_MENU_ID);
        }
 
        String SUB_MENU_NAME = entity.getSUB_MENU_NAME();
        if (SUB_MENU_NAME != null) {
            stmt.bindString(3, SUB_MENU_NAME);
        }
 
        Integer SHOW_SORT = entity.getSHOW_SORT();
        if (SHOW_SORT != null) {
            stmt.bindLong(4, SHOW_SORT);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public BoxSubMenu readEntity(Cursor cursor, int offset) {
        BoxSubMenu entity = new BoxSubMenu( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // SUB_MENU_ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // MAIN_MENU_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // SUB_MENU_NAME
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // SHOW_SORT
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BoxSubMenu entity, int offset) {
        entity.setSUB_MENU_ID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMAIN_MENU_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSUB_MENU_NAME(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSHOW_SORT(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(BoxSubMenu entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(BoxSubMenu entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
