package com.bjb.cultural.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOX_GROUP.
 */
public class BoxGroup {

    private String GROUP_ID;
    private String GROUP_NAME;
    private Integer SHOW_SORT;
    private String IMG_CLIENT;
    private String IMG_APK;

    public BoxGroup() {
    }

    public BoxGroup(String GROUP_ID, String GROUP_NAME, Integer SHOW_SORT, String IMG_CLIENT, String IMG_APK) {
        this.GROUP_ID = GROUP_ID;
        this.GROUP_NAME = GROUP_NAME;
        this.SHOW_SORT = SHOW_SORT;
        this.IMG_CLIENT = IMG_CLIENT;
        this.IMG_APK = IMG_APK;
    }

    public String getGROUP_ID() {
        return GROUP_ID;
    }

    public void setGROUP_ID(String GROUP_ID) {
        this.GROUP_ID = GROUP_ID;
    }

    public String getGROUP_NAME() {
        return GROUP_NAME;
    }

    public void setGROUP_NAME(String GROUP_NAME) {
        this.GROUP_NAME = GROUP_NAME;
    }

    public Integer getSHOW_SORT() {
        return SHOW_SORT;
    }

    public void setSHOW_SORT(Integer SHOW_SORT) {
        this.SHOW_SORT = SHOW_SORT;
    }

    public String getIMG_CLIENT() {
        return IMG_CLIENT;
    }

    public void setIMG_CLIENT(String IMG_CLIENT) {
        this.IMG_CLIENT = IMG_CLIENT;
    }

    public String getIMG_APK() {
        return IMG_APK;
    }

    public void setIMG_APK(String IMG_APK) {
        this.IMG_APK = IMG_APK;
    }

}
