package com.bjb.cultural.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOX_MAIN_MENU.
 */
public class BoxMainMenu {

    private String MAIN_MENU_ID;
    private String MAIN_MENU_NAME;
    private Integer SHOW_SORT;
    private Integer TYPE;

    public BoxMainMenu() {
    }

    public BoxMainMenu(String MAIN_MENU_ID, String MAIN_MENU_NAME, Integer SHOW_SORT, Integer TYPE) {
        this.MAIN_MENU_ID = MAIN_MENU_ID;
        this.MAIN_MENU_NAME = MAIN_MENU_NAME;
        this.SHOW_SORT = SHOW_SORT;
        this.TYPE = TYPE;
    }

    public String getMAIN_MENU_ID() {
        return MAIN_MENU_ID;
    }

    public void setMAIN_MENU_ID(String MAIN_MENU_ID) {
        this.MAIN_MENU_ID = MAIN_MENU_ID;
    }

    public String getMAIN_MENU_NAME() {
        return MAIN_MENU_NAME;
    }

    public void setMAIN_MENU_NAME(String MAIN_MENU_NAME) {
        this.MAIN_MENU_NAME = MAIN_MENU_NAME;
    }

    public Integer getSHOW_SORT() {
        return SHOW_SORT;
    }

    public void setSHOW_SORT(Integer SHOW_SORT) {
        this.SHOW_SORT = SHOW_SORT;
    }

    public Integer getTYPE() {
        return TYPE;
    }

    public void setTYPE(Integer TYPE) {
        this.TYPE = TYPE;
    }

}
