package com.bjb.cultural.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOX_RES.
 */
public class BoxRes {

    private String RES_ID;
    private String SUB_MENU_ID;
    private String CATEGORY_ID;
    private String FLG;
    private String TYPE;
    private String MY_FLG;
    private String IS_TOP;
    private String IS_REC;
    private String RES_NAME;
    private String RES_SORT_NAME;
    private String PATH;
    private String IMG;
    private String TOP_IMG;
    private String ACTOR;
    private String CAPTION;
    private String NOTICE;
    private String UPD_DATE;
    private String CRE_DATE;

    public BoxRes() {
    }

    public BoxRes(String RES_ID, String SUB_MENU_ID, String CATEGORY_ID, String FLG, String TYPE, String MY_FLG, String IS_TOP, String IS_REC, String RES_NAME, String RES_SORT_NAME, String PATH, String IMG, String TOP_IMG, String ACTOR, String CAPTION, String NOTICE, String UPD_DATE, String CRE_DATE) {
        this.RES_ID = RES_ID;
        this.SUB_MENU_ID = SUB_MENU_ID;
        this.CATEGORY_ID = CATEGORY_ID;
        this.FLG = FLG;
        this.TYPE = TYPE;
        this.MY_FLG = MY_FLG;
        this.IS_TOP = IS_TOP;
        this.IS_REC = IS_REC;
        this.RES_NAME = RES_NAME;
        this.RES_SORT_NAME = RES_SORT_NAME;
        this.PATH = PATH;
        this.IMG = IMG;
        this.TOP_IMG = TOP_IMG;
        this.ACTOR = ACTOR;
        this.CAPTION = CAPTION;
        this.NOTICE = NOTICE;
        this.UPD_DATE = UPD_DATE;
        this.CRE_DATE = CRE_DATE;
    }

    public String getRES_ID() {
        return RES_ID;
    }

    public void setRES_ID(String RES_ID) {
        this.RES_ID = RES_ID;
    }

    public String getSUB_MENU_ID() {
        return SUB_MENU_ID;
    }

    public void setSUB_MENU_ID(String SUB_MENU_ID) {
        this.SUB_MENU_ID = SUB_MENU_ID;
    }

    public String getCATEGORY_ID() {
        return CATEGORY_ID;
    }

    public void setCATEGORY_ID(String CATEGORY_ID) {
        this.CATEGORY_ID = CATEGORY_ID;
    }

    public String getFLG() {
        return FLG;
    }

    public void setFLG(String FLG) {
        this.FLG = FLG;
    }

    public String getTYPE() {
        return TYPE;
    }

    public void setTYPE(String TYPE) {
        this.TYPE = TYPE;
    }

    public String getMY_FLG() {
        return MY_FLG;
    }

    public void setMY_FLG(String MY_FLG) {
        this.MY_FLG = MY_FLG;
    }

    public String getIS_TOP() {
        return IS_TOP;
    }

    public void setIS_TOP(String IS_TOP) {
        this.IS_TOP = IS_TOP;
    }

    public String getIS_REC() {
        return IS_REC;
    }

    public void setIS_REC(String IS_REC) {
        this.IS_REC = IS_REC;
    }

    public String getRES_NAME() {
        return RES_NAME;
    }

    public void setRES_NAME(String RES_NAME) {
        this.RES_NAME = RES_NAME;
    }

    public String getRES_SORT_NAME() {
        return RES_SORT_NAME;
    }

    public void setRES_SORT_NAME(String RES_SORT_NAME) {
        this.RES_SORT_NAME = RES_SORT_NAME;
    }

    public String getPATH() {
        return PATH;
    }

    public void setPATH(String PATH) {
        this.PATH = PATH;
    }

    public String getIMG() {
        return IMG;
    }

    public void setIMG(String IMG) {
        this.IMG = IMG;
    }

    public String getTOP_IMG() {
        return TOP_IMG;
    }

    public void setTOP_IMG(String TOP_IMG) {
        this.TOP_IMG = TOP_IMG;
    }

    public String getACTOR() {
        return ACTOR;
    }

    public void setACTOR(String ACTOR) {
        this.ACTOR = ACTOR;
    }

    public String getCAPTION() {
        return CAPTION;
    }

    public void setCAPTION(String CAPTION) {
        this.CAPTION = CAPTION;
    }

    public String getNOTICE() {
        return NOTICE;
    }

    public void setNOTICE(String NOTICE) {
        this.NOTICE = NOTICE;
    }

    public String getUPD_DATE() {
        return UPD_DATE;
    }

    public void setUPD_DATE(String UPD_DATE) {
        this.UPD_DATE = UPD_DATE;
    }

    public String getCRE_DATE() {
        return CRE_DATE;
    }

    public void setCRE_DATE(String CRE_DATE) {
        this.CRE_DATE = CRE_DATE;
    }

}
