package com.bjb.cultural.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOX_SUB_MENU.
 */
public class BoxSubMenu {

    private String SUB_MENU_ID;
    private String MAIN_MENU_ID;
    private String SUB_MENU_NAME;
    private Integer SHOW_SORT;

    public BoxSubMenu() {
    }

    public BoxSubMenu(String SUB_MENU_ID, String MAIN_MENU_ID, String SUB_MENU_NAME, Integer SHOW_SORT) {
        this.SUB_MENU_ID = SUB_MENU_ID;
        this.MAIN_MENU_ID = MAIN_MENU_ID;
        this.SUB_MENU_NAME = SUB_MENU_NAME;
        this.SHOW_SORT = SHOW_SORT;
    }

    public String getSUB_MENU_ID() {
        return SUB_MENU_ID;
    }

    public void setSUB_MENU_ID(String SUB_MENU_ID) {
        this.SUB_MENU_ID = SUB_MENU_ID;
    }

    public String getMAIN_MENU_ID() {
        return MAIN_MENU_ID;
    }

    public void setMAIN_MENU_ID(String MAIN_MENU_ID) {
        this.MAIN_MENU_ID = MAIN_MENU_ID;
    }

    public String getSUB_MENU_NAME() {
        return SUB_MENU_NAME;
    }

    public void setSUB_MENU_NAME(String SUB_MENU_NAME) {
        this.SUB_MENU_NAME = SUB_MENU_NAME;
    }

    public Integer getSHOW_SORT() {
        return SHOW_SORT;
    }

    public void setSHOW_SORT(Integer SHOW_SORT) {
        this.SHOW_SORT = SHOW_SORT;
    }

}
