create table BOX_VERSION ( NAME TEXT, FLG TEXT, VERSION TEXT, UPD_DATE TEXT ); 
create table BOX_SETTING ( UPD_APP_FLG TEXT, UPD_RES_FLG TEXT ); 
create table BOX_UPDATE ( FLG TEXT ); 
create table ING_PROVINCE ( PROVINCEID TEXT, PROVINCENAME TEXT, PARENTCODE TEXT, AREACODE TEXT ); 
create table ING_CITY ( CITYID TEXT, CITYNAME TEXT, CITYPINYIN TEXT, PROVINCEID TEXT, LONGITUDE TEXT, LATITUDE TEXT ); 
create table BOX_INFO ( BOX_ID TEXT, COMPANY_ID TEXT, FLG TEXT, ENABLE_FLG TEXT, ACTIVATION_CODE TEXT, ACTIVATION_DATE TEXT, UPLOAD_DATE TEXT, UPD_DATE TEXT ); 
create table BOX_COMPANY ( COMPANY_ID TEXT, PROVINCE_ID TEXT, CITY_ID TEXT, COMPANY_NAME TEXT, COMPANY_ADDRESS TEXT, ZIP_CODE TEXT, USER_NAME TEXT, TEL_NO TEXT, MOBILE_NO TEXT, FLG TEXT, DEL_FLG TEXT ); 